/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class FramePerhitunganDiskon extends javax.swing.JFrame {
    
    private void syncSliderAndComboBox() {
    // Sync Slider to ComboBox (set combo box value based on slider position)
    sliderDiskon.addChangeListener(evt -> {
        // Ambil nilai dari slider (biasanya antara 0 dan 100)
        int sliderValue = sliderDiskon.getValue();
        
        // Set nilai ComboBox berdasarkan nilai slider
        cbbDiskon.setSelectedItem(String.valueOf(sliderValue));
    });

    // Sync ComboBox to Slider (set slider position based on combo box selection)
    cbbDiskon.addActionListener(evt -> {
        // Ambil nilai yang dipilih di combo box
        String selectedDiskon = (String) cbbDiskon.getSelectedItem();
        
        // Set posisi slider berdasarkan nilai yang dipilih di combo box
        int selectedDiskonValue = Integer.parseInt(selectedDiskon);
        sliderDiskon.setValue(selectedDiskonValue);
    });
}

    
private void hitungDiskon() {
    try {
        // Ambil harga dari txtFieldHarga dan ubah menjadi double
        double harga = Double.parseDouble(txtFieldHarga.getText());

        // Ambil kupon dari kuponTxt
        String kupon = kuponTxt.getText();

        // Ambil diskon dari sliderDiskon
        int diskonSlider = sliderDiskon.getValue(); // Ambil nilai slider (biasanya antara 0 dan 100)

        // Ambil diskon dari ComboBox (sebagai fallback jika slider tidak digunakan)
        String diskonSelected = (String) cbbDiskon.getSelectedItem();
        double diskonComboBox = Double.parseDouble(diskonSelected);

        // Tentukan diskon yang dipilih: jika slider digeser, gunakan nilai slider
        double diskon = (diskonSlider > 0) ? diskonSlider : diskonComboBox;

        // Mengecek apakah kupon yang dimasukkan adalah "bagus123"
        String riwayat = "Harga: " + harga + "\n";
        
        if (kupon.equals("bagus123")) {
            // Tambahkan diskon ekstra (misalnya 10%) jika kupon valid
            diskon += 10;  // Menambahkan 10% jika kupon valid
            riwayat += "Kupon Valid! Diskon ekstra 10% diterapkan.\n";
        }

        // Hitung total diskon
        double diskonAmount = harga * diskon / 100;
        double hargaSetelahDiskon = harga - diskonAmount;

        // Menambahkan riwayat hasil perhitungan
        riwayat += "Diskon yang diterapkan: " + diskon + "%\n"
                 + "Jumlah Diskon: " + diskonAmount + "\n"
                 + "Harga Setelah Diskon: " + hargaSetelahDiskon + "\n\n";

        // Menambahkan riwayat ke txtArea
        txtArea.append(riwayat);  // Gunakan append() untuk menambah riwayat, bukan setText()
        
    } catch (NumberFormatException e) {
        txtArea.append("Input harga tidak valid.\n\n");
    }
}


    /**
     * Creates new form FramePerhitunganDiskon
     */
    public FramePerhitunganDiskon() {
        initComponents();
        syncSliderAndComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kuponTxt = new javax.swing.JTextField();
        sliderDiskon = new javax.swing.JSlider();
        cbbDiskon = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtFieldHarga = new javax.swing.JTextField();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Harga: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Slider Diskon:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Pilih Diskon: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Kupon ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        jPanel1.add(jLabel4, gridBagConstraints);

        kuponTxt.setText("Input Kupon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        jPanel1.add(kuponTxt, gridBagConstraints);

        sliderDiskon.setPaintLabels(true);
        sliderDiskon.setPaintTicks(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        jPanel1.add(sliderDiskon, gridBagConstraints);

        cbbDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "40", "50" }));
        cbbDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbDiskonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        jPanel1.add(cbbDiskon, gridBagConstraints);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        jPanel1.add(btnHitung, gridBagConstraints);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        jPanel1.add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtFieldHarga, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    hitungDiskon();        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void cbbDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbDiskonItemStateChanged
    hitungDiskon();        // TODO add your handling code here:
    }//GEN-LAST:event_cbbDiskonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePerhitunganDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cbbDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kuponTxt;
    private javax.swing.JSlider sliderDiskon;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtFieldHarga;
    // End of variables declaration//GEN-END:variables
}
